GET http://localhost:3000/recurso

###

GET http://localhost:3000/recurso/1

###

POST http://localhost:3000/recurso HTTP/1.1
Content-Type: application/json

{
    "estado": "libre"
}

###
PUT http://localhost:3000/recursos/2 HTTP/1.1
Content-Type: application/json

{
    "estado": "ocupado"
}
###
DELETE http://localhost:3000/recursos/3 HTTP/1.1


