GET http://localhost:3000/reservas

###

GET http://localhost:3000/reserva/2

###

POST http://localhost:3000/reserva HTTP/1.1
Content-Type: application/json

{
    "estado": "libre"
}

###
PUT http://localhost:3000/reserva/2 HTTP/1.1
Content-Type: application/json

{
    "estado": "ocupado"
}
###
DELETE http://localhost:3000/reserva/3 HTTP/1.1


